# Generated by Django 4.2.5 on 2023-09-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brangroupmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BranGrCode', models.CharField(max_length=6)),
                ('BranGrName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='compinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('pin', models.IntegerField()),
                ('phoneno', models.IntegerField()),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=30)),
                ('vattin', models.CharField(max_length=10)),
                ('csttin', models.CharField(max_length=10)),
                ('excise', models.CharField(max_length=10)),
                ('pfno', models.IntegerField()),
                ('esino', models.IntegerField()),
                ('EPFPER', models.FloatField()),
                ('EPSPER', models.FloatField()),
                ('MAXEPS', models.FloatField()),
                ('ESIPER', models.FloatField()),
                ('LabourWealfare1', models.IntegerField()),
                ('LabourWealfare2', models.IntegerField()),
                ('LabourWealfare3', models.IntegerField()),
                ('LabourWealfare4', models.IntegerField()),
                ('LabourWealfare5', models.IntegerField()),
                ('TaDaper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dailyattendancesmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordNo', models.IntegerField()),
                ('AttendanceDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='empfandf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.IntegerField()),
                ('DateOfRelieve', models.DateTimeField()),
                ('ActualWorkDays', models.IntegerField()),
                ('WeeklyOff', models.IntegerField()),
                ('CompanyOff', models.IntegerField()),
                ('Holidays', models.IntegerField()),
                ('ElBalance', models.IntegerField()),
                ('TotalDays', models.IntegerField()),
                ('NetPayable', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Remark', models.CharField(max_length=30)),
                ('RecoverBal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Note', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='employeemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=10)),
                ('empshortname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leaveemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicpay', models.FloatField()),
                ('leaveencashdate', models.DateField()),
                ('leaveencashday', models.FloatField()),
                ('ltcblog', models.IntegerField()),
                ('ltcfrom', models.IntegerField()),
                ('ltcto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='otherFacilitiesMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.IntegerField()),
                ('OfAmt1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OfDescription1', models.CharField(max_length=10)),
                ('OfAmt2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OfDescription2', models.CharField(max_length=10)),
                ('OfAmt3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OfDescription3', models.CharField(max_length=10)),
                ('OfAmt4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OfDescription4', models.CharField(max_length=10)),
                ('OfAmt5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OfDescription5', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='saladvcalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.IntegerField()),
                ('EmpCode', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('BasicPay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Attendance', models.IntegerField()),
                ('DateOn', models.DateTimeField()),
                ('AccumulateSalAdv', models.DecimalField(decimal_places=2, max_digits=6)),
                ('SalAdv', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='shiftmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftname', models.CharField(max_length=10)),
                ('shiftcode', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='statemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statecode', models.IntegerField()),
                ('statename', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usermaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('leavepostpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation1',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation2',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation3',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation4',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation5',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpCode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate2',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate3',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate4',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate5',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate2',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate3',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate4',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate5',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer1',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer2',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer3',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer4',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer5',
            field=models.CharField(max_length=6),
        ),
    ]
