# Generated by Django 4.2.5 on 2023-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_brangroupmaster_compinfo_dailyattendancesmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='Designation5',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate3',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate4',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpFromDate5',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate2',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate3',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate4',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='EmpToDate5',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeexperience',
            name='PrvEmployer5',
            field=models.CharField(max_length=50),
        ),
    ]
